import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import {PGlite} from './.test-tools/pglite/package/dist/index.js';
const db=new PGlite();
const read=async n=>(await fs.readFile(new URL(n,import.meta.url),'utf8')).replace(/\r\n/g,'\n');
const migration=await read('09_ojt_deadline_alerts.sql');
const full=await read('OJT_RPA_FULL_SUPABASE.sql');
const body=migration.replace(/^(?:BEGIN|COMMIT);\s*$/gm,'');
const reject=async (s,c)=>assert.rejects(db.exec(s),e=>e.code===c);
try {
 await db.exec('CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role BYPASSRLS;');
 assert.ok(full.includes(body)); await db.exec(full.replace(body,''));
 await db.exec(`INSERT INTO "Users" ("Username","PasswordHash","Email","FullName","RoleID") SELECT 'alert-test','fixture','alert@example.invalid','Fixture',"RoleID" FROM "Roles" WHERE "RoleCode"='STUDENT';
 INSERT INTO "Students" ("UserID","StudentCode") VALUES (1,'TEST');`);
 await db.exec(migration);
 assert.equal((await db.query('SELECT count(*)::int n FROM "Students"')).rows[0].n,1);
 assert.equal((await db.query('SELECT count(*)::int n FROM "OJTAlertRules" WHERE NOT "IsEnabled"')).rows[0].n,4);
 await reject(migration,'P0001'); await db.exec('ROLLBACK');
 await reject('UPDATE "OJTAlertRules" SET "IsEnabled"=true WHERE "RuleID"=1','23514');
 await db.exec(`INSERT INTO "AcademicYears" ("YearCode") VALUES ('TEST');
 INSERT INTO "OJTSemesters" ("AcademicYearID","SemesterCode","Name") VALUES (1,'S1','Semester 1'),(1,'S2','Semester 2');
 INSERT INTO "OJTAlertTargets" ("StudentID","OJTSemesterID","Source","ConfirmedBy") VALUES (1,1,'STAFF',1),(1,2,'STAFF',1);
 INSERT INTO "OJTAlertCheckRuns" ("IdempotencyKey","OJTSemesterID","AsOf","EngineVersion") VALUES ('r1',1,now(),'v1');`);
 const evaluation=`INSERT INTO "OJTAlertEvaluations" ("RunID","TargetID","OJTSemesterID","RuleID","Scope","Outcome","ReasonCode","Evidence","RuleSnapshot") VALUES (1,1,1,1,'STUDENT','TRIGGERED','TEST','{}','{}') RETURNING "EvaluationID"`;
 await reject(evaluation.replace('(1,1,1,1,','(1,2,1,1,'),'23503');
 const e=(await db.query(evaluation)).rows[0].EvaluationID;
 await reject(evaluation,'23505');
 const alert=`INSERT INTO "OJTAlerts" ("TargetID","RuleID","ScopeKey","TriggerEvaluationID","Severity","Title","Message") VALUES (1,1,'STUDENT',${e},'WARNING','Test','Missing requirement')`;
 await db.exec(alert); await reject(alert,'23505');
 await reject(`UPDATE "OJTAlertEvaluations" SET "Outcome"='UNKNOWN' WHERE "EvaluationID"=${e}`,'23503');
 await reject('UPDATE "OJTAlerts" SET "Status"=\'RESOLVED\'','23514');
 await db.exec(`INSERT INTO "Notifications" ("UserID","Title") VALUES (1,'Test');
 INSERT INTO "OJTAlertDeliveries" ("AlertID","RecipientUserID","Channel","IdempotencyKey","NotificationID") SELECT "AlertID",1,'IN_APP','d1',1 FROM "OJTAlerts";`);
 await reject(`INSERT INTO "OJTAlertDeliveries" ("AlertID","RecipientUserID","Channel","IdempotencyKey") SELECT "AlertID",1,'EMAIL','d1' FROM "OJTAlerts"`,'23505');
 await reject('UPDATE "OJTAlertDeliveries" SET "Status"=\'SENT\'','23514');
 // A real task must match the target's student and semester.
 await db.exec(`INSERT INTO "Enterprises" ("EnterpriseCode","Name") VALUES ('TEST','Test');
 INSERT INTO "InternshipPositions" ("EnterpriseID","OJTSemesterID","Title") VALUES (1,1,'Intern');
 INSERT INTO "OJTRegistrations" ("StudentID","OJTSemesterID") VALUES (1,1);
 INSERT INTO "StudentEnterpriseCoordination" ("RegistrationID","EnterpriseID","PositionID","CoordinatedBy") VALUES (1,1,1,1);
 INSERT INTO "InternshipAssignments" ("CoordinationID","StudentID","EnterpriseID","PositionID") VALUES (1,1,1,1);
 INSERT INTO "InternshipTasks" ("AssignmentID","TaskName") VALUES (1,'Task');
 INSERT INTO "OJTAlertCheckRuns" ("IdempotencyKey","OJTSemesterID","AsOf","EngineVersion") VALUES ('r2',2,now(),'v1');`);
 const task=`INSERT INTO "OJTAlertEvaluations" ("RunID","TargetID","OJTSemesterID","RuleID","Scope","TaskID","Outcome","ReasonCode","Evidence","RuleSnapshot") VALUES (1,1,1,4,'TASK',1,'TRIGGERED','OVERDUE','{}','{}')`;
 await db.exec(task);
 await reject(task.replace('(1,1,1,4,','(2,2,2,4,'),'P0001');
 await db.exec('SET ROLE anon'); await reject('SELECT * FROM "OJTAlerts"','42501'); await db.exec('RESET ROLE');
 const result={status:'PASS',engine:'PGlite local PostgreSQL',checks:['migration preserves existing student','four rules disabled by default; approval required','repeat migration guarded','semester and task context enforced','evaluation and active alert deduplication','cannot replace triggering evidence with UNKNOWN','closed alert and sent delivery timestamps required','delivery idempotency','anonymous access denied']};
 await fs.writeFile(new URL('ojt_alert_test_results.json',import.meta.url),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
}catch(e){console.error(e.message,e.code,e.detail);process.exitCode=1;}finally{await db.close();}
